@startuml
'https://plantuml.com/sequence-diagram

autonumber

title HTTP Chatroom User Initialization
index.html -> ChatAPI: HTTP POST
note left
HTTP POST
Content-Type: application/x-www-form-urlencoded
username="username"&post_type=register
end note
ChatAPI -> index.html: HTTP 302: Redirect: "/chatroom.html"
note right
HTTP 302 Redirect
Location: /chatroom.html
Set-Cookie: "user"="username"
end note
index.html -> chatroom.html: HTTP GET
note left
HTTP GET
Cookie: "user"="username"
end note
newpage  Sending Message Sequence
chatroom.html -> ChatAPI: js: sendButton Event
note right
HTTP POST
Content-Type: text/plain
Cookie: "user"="usernameA"

"this is a message"
end note
ChatAPI -> "chatroom.html": HTTP 200
note left
(Option 1) redirect if cookie is invalid
forcing user to register and obtain a cookie

HTTP 302 Redirect
Location: /index.html

(Option 2)  Message received successfully

HTTP 200
Content-Type = text/html
Content-Length = 0
end note
newpage Polling Message Sequence
chatroom.html -> ChatAPI: poll.js: fetch()
note right
HTTP GET
Cookie: "user" = "usernameA"
end note
ChatAPI -> chatroom.html: HTTP 200
note left
(Option 1) Message available for user,

HTTP 200
Content-Type=application/json

{"user" : "Andy", "message" : "wassup"}

(Option 2) No message for user

HTTP 200
Content-Length=0
Content-Type=application/json

(Option 3) redirect if cookie is invalid
forcing user to register and obtain a cookie

HTTP 302 Redirect
Location: /index.html
end note
@enduml